trigger:
- main  # Triggers the pipeline on pushes to the main branch

# 1. USE THE SELF-HOSTED AGENT POOL
pool:
  name: sonarqube  # This must be the name of the pool where your self-hosted agent is registered

variables:
  sonarProjectKey: 'secure-pipeline'  # Must be unique in your SonarQube instance
  sonarProjectName: 'secure-pipeline'
  nodeVersion: '18.x' # Specify your Node.js version

steps:

# 2. SET UP NODE.JS
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

# 3. INSTALL PROJECT DEPENDENCIES
- script: |
    npm install
  displayName: 'npm install'
  workingDirectory: '/home/youssef/secure/3tier-nodejs/frontend'
  # Using 'npm ci' for clean, reproducible installs in CI environments


- task: SonarQubePrepare@7
  displayName: 'SonarQube: Prepare Analysis'
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'cli'  # Note: Sometimes it's 'CLI' instead of 'cli' in v5
    configMode: 'manual'
    cliProjectKey: '$(sonarProjectKey)'
    cliProjectName: '$(sonarProjectName)'
    cliSources: 'frontend'
    extraProperties: |
      sonar.host.url=http://localhost:9000
      sonar.language=js
      sonar.sources=.
      sonar.exclusions=**/node_modules/**, **/coverage/**, **/dist/**
      # Still include these to be safe
      sonar.branch.name=
      sonar.branch.target=

# 6. RUN THE SONARQUBE ANALYSIS
- task: SonarQubeAnalyze@7
  displayName: 'SonarQube: Run Analysis'
  # This task executes the sonar-scanner, which collects data and sends it to the server.

# 7. PUBLISH THE ANALYSIS RESULTS TO SONARQUBE SERVER
- task: SonarQubePublish@7
  displayName: 'SonarQube: Publish Results'
  # This task finalizes the analysis and triggers processing on the SonarQube server.
  # The Quality Gate is calculated after this step.

# 8. THE SAST GATE: CHECK THE QUALITY GATE STATUS
- task: SonarQubeQualityGateCheck@1
  displayName: 'SonarQube: Check Quality Gate'
  inputs:
    # Wait for SonarQube server to process the results and compute the gate
    pollingTimeoutSec: '300' # Wait up to 5 minutes
    # This task will FAIL THE BUILD if the Quality Gate fails.
    # This is your SAST gate in action.
