trigger:
- main  # Triggers the pipeline on pushes to the main branch

# 1. USE THE SELF-HOSTED AGENT POOL
pool:
  name: sonarqube  # This must be the name of the pool where your self-hosted agent is registered

variables:
  sonarProjectKey: 'secure-pipeline'  # Must be unique in your SonarQube instance
  sonarProjectName: 'secure-pipeline'
  nodeVersion: '18.x' # Specify your Node.js version

steps:

# 2. SET UP NODE.JS
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

# 3. INSTALL PROJECT DEPENDENCIES
- script: |
    npm install
  displayName: 'npm install'
  workingDirectory: '/home/youssef/secure/3tier-nodejs/frontend'
  # Using 'npm ci' for clean, reproducible installs in CI environments


- task: SonarQubePrepare@7
  displayName: 'SonarQube: Prepare Analysis'
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'cli'  # Note: 
    configMode: 'manual'
    cliProjectKey: '$(sonarProjectKey)'
    cliProjectName: '$(sonarProjectName)'
    cliSources: '/home/youssef/secure/3tier-nodejs/frontend'
    extraProperties: |
      sonar.host.url=http://localhost:9000
      sonar.exclusions=**/node_modules/**, **/coverage/**, **/dist/**

- script: |
    echo "Sanitizing SONARQUBE_SCANNER_PARAMS..."
    export SONARQUBE_SCANNER_PARAMS=$(echo "$SONARQUBE_SCANNER_PARAMS" | sed 's/"sonar.branch.name":"[^"]*",\?//g')
    echo "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$SONARQUBE_SCANNER_PARAMS"
  displayName: 'Remove sonar.branch.name for Community Edition'

# 6. RUN THE SONARQUBE ANALYSIS
- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
  displayName: 'RUN THE SONARQUBE ANALYSIS'

# 7. PUBLISH THE ANALYSIS RESULTS TO SONARQUBE SERVER
- task: SonarQubePublish@7
  displayName: 'SonarQube: Publish Results'
  # This task finalizes the analysis and triggers processing on the SonarQube server.
  # The Quality Gate is calculated after this step.

# 8. THE SAST GATE: CHECK THE QUALITY GATE STATUS
- task: SonarQubeQualityGateCheck@1
  displayName: 'SonarQube: Check Quality Gate'
  inputs:
    pollingTimeoutSec: '300'
